<a href="https://colab.research.google.com/github/Laxmiprasanna2930/pytorch_fundamentals/blob/main/pytorch_fundamentals_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Manipulating Tensors (tensor operations)
Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication







In [73]:
# Create a tensor and add 10 to it

In [74]:
import torch

In [75]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [76]:
# Multiply tensor by 10

In [77]:
tensor=tensor*10
tensor

tensor([10, 20, 30])

In [78]:
# Subtract 10

In [79]:
tensor=tensor-10
tensor

tensor([ 0, 10, 20])

In [80]:
# Pytorch in-built functions

In [81]:
torch.mul(tensor,10)

tensor([  0, 100, 200])

In [82]:
torch.add(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication
Two ways:
1. Element-wise multiplication
2. Matrix multiplication (dot product)



In [83]:
# Element wise multiplication

In [84]:
print(tensor,"*",tensor)
print(f"Equals:{tensor *tensor}")

tensor([ 0, 10, 20]) * tensor([ 0, 10, 20])
Equals:tensor([  0, 100, 400])


In [85]:
# Matrix multiplication

In [86]:
torch.matmul(tensor,tensor)

tensor(500)

In [87]:
tensor @ tensor

tensor(500)

In [88]:
%%time
value =0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(500)
CPU times: user 2 ms, sys: 0 ns, total: 2 ms
Wall time: 3.88 ms


In [89]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 59 µs, sys: 0 ns, total: 59 µs
Wall time: 61.3 µs


tensor(500)

### One of the most common errors in deep learning: shape errors

In [90]:
# Shapes for matrix multiplication

In [92]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]])
tensor_B=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])
torch.mm(tensor_A,tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [93]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues,we can manipulate the shape of one of our tensors using a **transpose**.
A **transpose** switches the axes or dimensions of a given tensor.


In [94]:
tensor_B.T,tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [95]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [96]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [97]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [98]:
torch.matmul(tensor_A,tensor_B.T).shape

torch.Size([3, 3])

In [99]:
# The matrix multiplication operation works when tensor_B is transposed

In [100]:
print(f"Original shapes:tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New shapes:tensor_A={tensor_A.shape}(same shape as above),tensor_B.T ={tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\nOutput shape:{output.shape}")

Original shapes:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New shapes:tensor_A=torch.Size([3, 2])(same shape as above),tensor_B.T =torch.Size([2, 3])
Multiplying:torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape:torch.Size([3, 3])


### Finding the min,max,mean,sum,etc(tensor aggregation)

In [101]:
# Create a tensor

In [102]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [103]:
# Find the min

In [104]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [105]:
# Find the max

In [106]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [107]:
# find the mean

In [108]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [109]:
# Find the sum

In [110]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))