<a href="https://colab.research.google.com/github/Laxmiprasanna2930/pytorch_fundamentals/blob/main/Pytorch_fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch Fundamentals

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


### Introduction to Tensors                                                 ## Creating tensors



In [3]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# Matrix
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# Tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [17]:
# Create a random tensor of size(3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.1975, 0.3660, 0.9567, 0.3223],
        [0.7978, 0.8694, 0.8383, 0.7113],
        [0.9676, 0.5311, 0.6207, 0.1988]])

In [18]:
random_tensor.ndim

2

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,colour channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [20]:
torch.rand(3,3)

tensor([[0.9587, 0.3342, 0.6791],
        [0.9941, 0.2015, 0.9107],
        [0.3551, 0.4992, 0.1942]])

In [21]:
# create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
# create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [24]:
ones.dtype

torch.float32

In [25]:
random_tensor.dtype

torch.float32