<a href="https://colab.research.google.com/github/Laxmiprasanna2930/pytorch_fundamentals/blob/main/Pytorch_fundamentals_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Pytorch Fundamentals

In [26]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


### Introduction to Tensors                                                 ## Creating tensors



In [27]:
#scalar

In [28]:
scalar=torch.tensor(7)
scalar

tensor(7)

In [29]:
scalar.ndim

0

In [30]:
# get tensor back as Python int

In [31]:
scalar.item()

7

In [32]:
# Vector

In [33]:
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [34]:
vector.ndim

1

In [35]:
vector.shape

torch.Size([2])

In [36]:
# Matrix

In [37]:
MATRIX=torch.tensor([[7,8],
                     [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [38]:
MATRIX.ndim

2

In [39]:
MATRIX[0]

tensor([7, 8])

In [40]:
MATRIX.shape

torch.Size([2, 2])

In [41]:
# Tensor

In [42]:
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [43]:
TENSOR.ndim

3

In [44]:
TENSOR.shape

torch.Size([1, 3, 3])

In [45]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [46]:
# Create a random tensor of size(3,4)

In [47]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5510, 0.1433, 0.0414, 0.5361],
        [0.5506, 0.2917, 0.0761, 0.4542],
        [0.4361, 0.4336, 0.5324, 0.2937]])

In [48]:
random_tensor.ndim

2

In [49]:
# Create a random tensor with similar shape to an image tensor

In [50]:
random_image_size_tensor=torch.rand(size=(224,224,3)) #height,width,colour channels(R,G,B)
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [51]:
torch.rand(3,3)

tensor([[0.7860, 0.0912, 0.9181],
        [0.3133, 0.5263, 0.2772],
        [0.9720, 0.6961, 0.7127]])

In [52]:
# create a tensor of all zeros

In [53]:
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [54]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [55]:
# create a tensor of all ones

In [56]:
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [57]:
ones.dtype

torch.float32

In [58]:
random_tensor.dtype

torch.float32