<a href="https://colab.research.google.com/github/Laxmiprasanna2930/pytorch_fundamentals/blob/main/pytorch_fundamentals_04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Finding the positional min and max

In [2]:
import torch
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [5]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs

In [3]:
x.argmin()

tensor(0)

In [4]:
x[0]

tensor(0)

In [6]:
# Find the position in tensor that has the miximum value with argmax()

In [7]:
x.argmax()

tensor(9)

In [8]:
x[9]

tensor(90)

### Reshaping,stacking,squeezing and unsqueezing tensors
* Reshaping- reshapes an input tensor to a defined shape
* view- return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking- combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze- removes all 'l' dimensions from a tensor
* Unsqueeze- add a 'l' dimension to a target tensor
* Permute- return a view of the input with dimensions permuted (swapped) in a certain way







In [9]:
# create a tensor

In [10]:
import torch
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [12]:
# Add an extra dimension

In [28]:
x_reshaped=x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [29]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [15]:
# Change the view

In [16]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [17]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)

In [18]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [19]:
# stack tensors on top of each other

In [25]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [26]:
x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [23]:
# torch.squeeze()-removes all single dimensions from a target tensor

In [34]:
print(f"previous tensor:{x_reshaped}")
print(f"previous shape:{x_reshaped.shape}")

previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape:torch.Size([1, 9])


In [35]:
# Remove extra dimension from x_reshaped

In [36]:
x_squeezed=x_reshaped.squeeze()
print(f"\nnew tensor:{x_squeezed}")
print(f"new shape:{x_squeezed.shape}")


new tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
new shape:torch.Size([9])


In [31]:
x_reshaped.shape

torch.Size([1, 9])

In [32]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
x_reshaped.squeeze().shape

torch.Size([9])

In [37]:
# torch.unsqueeze()-adds a single dimension to a target at a specific dim(dimension)

In [38]:
print(f"previous target:{x_squeezed}")
print(f"previous shape:{x_squeezed.shape}")

previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape:torch.Size([9])


In [39]:
# Adds an extra dimension with unsqueeze

In [40]:
x_unsqueezed=x_squeezed.unsqueeze(dim=0)
print(f"\n new tensor:{x_unsqueezed}")
print(f"new shape:{x_unsqueezed.shape}")


 new tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
new shape:torch.Size([1, 9])


In [41]:
# torch.permute- rearranges the dimensions of a target tensor in a specified order

In [42]:
x_original=torch.rand(size=(224,224,3)) # [height,width,colour_channels]

In [43]:
# Permute the original tensor to rearrange the axis(or dim) oder

In [44]:
x_permuted=x_original.permute(2,0,1) # shifts axis 0->1, 1->2,2->0
print(f"previous shape:{x_original.shape}")
print(f"new shape:{x_permuted.shape}") # [colour_channels,height,width]

previous shape:torch.Size([224, 224, 3])
new shape:torch.Size([3, 224, 224])


In [45]:
x_original

tensor([[[0.0582, 0.5677, 0.9094],
         [0.5063, 0.5961, 0.0927],
         [0.0621, 0.2981, 0.8228],
         ...,
         [0.2941, 0.5485, 0.6724],
         [0.8931, 0.7217, 0.3237],
         [0.9670, 0.9151, 0.6672]],

        [[0.6737, 0.8317, 0.3779],
         [0.2487, 0.1329, 0.3858],
         [0.5328, 0.6320, 0.1513],
         ...,
         [0.1608, 0.8489, 0.1672],
         [0.8792, 0.7294, 0.4960],
         [0.3879, 0.3090, 0.2666]],

        [[0.3912, 0.0672, 0.5694],
         [0.2962, 0.8405, 0.3308],
         [0.6359, 0.8276, 0.1851],
         ...,
         [0.0893, 0.4911, 0.6893],
         [0.5512, 0.8106, 0.0113],
         [0.0311, 0.8149, 0.5321]],

        ...,

        [[0.1602, 0.5803, 0.7439],
         [0.1946, 0.2718, 0.1945],
         [0.6293, 0.0932, 0.6653],
         ...,
         [0.2343, 0.9398, 0.2809],
         [0.8449, 0.1629, 0.2314],
         [0.5569, 0.4752, 0.4297]],

        [[0.3423, 0.4292, 0.4991],
         [0.8971, 0.8844, 0.9633],
         [0.

In [48]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [50]:
# create a tensor

In [51]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [52]:
# Index on our new tensor

In [53]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
# Index on middle bracket (dim=1)

In [55]:
x[0][0]

tensor([1, 2, 3])

In [56]:
# Index on the  most inner bracket (last dimension)

In [57]:
x[0][0][0]

tensor(1)

In [61]:
x[0][1][1]

tensor(5)

In [62]:
# You can also use ":" to select "all" of a target dimension

In [63]:
x[:,0]

tensor([[1, 2, 3]])

In [64]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension

In [65]:
x[:,:,1]

tensor([[2, 5, 8]])

In [66]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension

In [67]:
x[:,1,1]

tensor([5])

In [68]:
# Get index of 0 of 0th and 1st dimension and all values of 2nd dimension

In [69]:
x[0,0,:]

tensor([1, 2, 3])

In [70]:
# Index on x to return 9

In [73]:
print(x[0][2][2])

tensor(9)


In [74]:
# index on x to return 3,6,9

In [75]:
print(x[:,:,2])

tensor([[3, 6, 9]])


In [76]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

### Pytorch tensors & NumPy

In [77]:
# Numpy array to tensor

In [84]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
array.dtype

dtype('float64')

In [80]:
tensor.dtype

torch.float64

In [81]:
torch.arange(1.0,8.0).dtype

torch.float32

In [85]:
# change the value of array,what will this do to 'tensor'?

In [86]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [87]:
# Tensor to NumPy array

In [88]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [89]:
numpy_tensor.dtype

dtype('float32')

In [90]:
# change the tensor what happens to 'numpy_tensor'?

In [91]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)

In [92]:
torch.rand(3,3)

tensor([[0.5743, 0.6914, 0.4036],
        [0.9049, 0.5656, 0.2234],
        [0.3939, 0.0994, 0.7086]])

In [93]:
import torch
# create two random tensors

In [94]:
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.4345, 0.8681, 0.6574, 0.5210],
        [0.9028, 0.1226, 0.3195, 0.6705],
        [0.5983, 0.9517, 0.3267, 0.3714]])
tensor([[0.9161, 0.6915, 0.4745, 0.3576],
        [0.4734, 0.3935, 0.0101, 0.7574],
        [0.9161, 0.2783, 0.1430, 0.9589]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [95]:
# Make some random but reproducible tensors

In [96]:
import torch
# set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [97]:
import torch
# set the random seed
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
