<a href="https://colab.research.google.com/github/Laxmiprasanna2930/pytorch_fundamentals/blob/main/pytorch_fundamentals_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Creating a range of tensors and tensors-like

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [2]:
# Use torch.range()

In [3]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
one_to_ten=torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# Use torch.range() and get deprecated message,use torch.arange

In [6]:
one_to_ten=torch.arange(start=0,end=1000,step=100)
one_to_ten

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [7]:
# Creating tensors like

In [8]:
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [9]:
# Float 32 tensor

In [10]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [11]:
float_32_tensor.dtype

torch.float32

In [12]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [13]:
from os import F_TLOCK
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, #what datatype is the tensor (e.g. float32 or float16)
                             device=None, # what device is your tensor on
                             requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [14]:
float_32_tensor.dtype

torch.float32

In [15]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [16]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [17]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [18]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [19]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype- to do get datatype from a tensor,can use tensor.dtype
2. Tensors not right shape- to get shape from a tensor,can use tensor.shape
3. Tensors not on the right device - to get device from a tensor,can use tensor.device





In [20]:
# Create a tensor

In [21]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.4823, 0.4881, 0.0741, 0.1078],
        [0.7163, 0.7657, 0.3102, 0.1751],
        [0.4693, 0.1156, 0.7169, 0.5336]])

In [22]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [23]:
some_tensor.size()

torch.Size([3, 4])

In [24]:
# Find out details about some tensor

In [25]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.4823, 0.4881, 0.0741, 0.1078],
        [0.7163, 0.7657, 0.3102, 0.1751],
        [0.4693, 0.1156, 0.7169, 0.5336]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on:cpu
